SELECT
    name
FROM
    v$datafile;

SELECT
    tablespace_name,
    status,
    contents
FROM
    user_tablespaces;

DROP TABLESPACE manu_tbs_01 INCLUDING CONTENTS CASCADE CONSTRAINTS;

CREATE TABLESPACE manu_tbs_01
    DATAFILE 'C:\APP\AC:\APP\ADMIN\PRODUCT\23AI\ORADATA\FREE\FREEPDB1\DATABASE\MANU_TBS_01.DBF' SIZE 10M REUSE
    AUTOEXTEND ON NEXT 10M MAXSIZE 50M;

SELECT
    name
FROM
    v$datafile;