CREATE TABLE EMPLOYEE_INCOME
(EMPID NUMBER(10),
NAME VARCHAR2(20),
SALARY NUMBER(10),
department VARCHAR2(20));

INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (1, 'Bill', 10000, 'HR');
INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (2, 'Mike', 20000, 'MARKETING');
INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (3, 'Samson', 30000, 'FINANCE');
INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (4, 'Kevin', 50000, 'IT');

INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (5, 'Bill1', 20000, 'HR');
INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (6, 'Mike1', 30000, 'MARKETING');
INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (7, 'Samson1', 40000, 'FINANCE');
INSERT INTO EMPLOYEE_INCOME (EMPID, NAME, SALARY, department) VALUES (8, 'Kevin1', 60000, 'IT');

SELECT * FROM EMPLOYEE_INCOME;

SELECT * FROM EMPLOYEE_INCOME where (department, salary) in (select department, max (salary) from EMPLOYEE_INCOME group by department);

