--con_SYS_23ai_free

ALTER PLUGGABLE DATABASE shardcat_pdb CLOSE;

ALTER PLUGGABLE DATABASE shardcat_pdb UNPLUG INTO 'C:\APP\ADMIN\PRODUCT\23AI\ORADATA\FREEpdb2.xml';

DROP PLUGGABLE DATABASE shardcat_pdb;

CREATE PLUGGABLE DATABASE shardcat_pdb
    ADMIN USER sysdba IDENTIFIED BY pdb2 CREATE_FILE_DEST = 'C:\APP\ADMIN\PRODUCT\23AI\ORADATA\FREE';

ALTER PLUGGABLE DATABASE shardcat_pdb OPEN;