DROP TABLE veactor_product; -- if exists

CREATE TABLE veactor_product (
    product_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    product_name VARCHAR2(50),
    description  VARCHAR2(50),
    v_embedding  VECTOR(3, FLOAT32)
);

INSERT INTO veactor_product (
    product_name,
    description,
    v_embedding
) VALUES ( 'P1',
           'P1 Description',
           '[0.12, 0.13, 0.14]' );

INSERT INTO veactor_product (
    product_name,
    description,
    v_embedding
) VALUES ( 'P2',
           'P2 Description',
           '[0.22, 0.23, 0.24]' );

INSERT INTO veactor_product (
    product_name,
    description,
    v_embedding
) VALUES ( 'P3',
           'P3 Description',
           '[0.32, 0.33, 0.34]' );

COMMIT;

SELECT
    product_name,
    description,
    vector_distance(v_embedding, '[0.10, 0.11, 0.15]', cosine) AS distance
FROM
    veactor_product
ORDER BY
    distance
FETCH FIRST 2 ROWS ONLY;