-- con_SYS_23ai_free

CREATE PLUGGABLE DATABASE pdb2
    ADMIN USER sysdba IDENTIFIED BY pdb2 CREATE_FILE_DEST = 'C:\APP\ADMIN\PRODUCT\23AI\ORADATA\FREE';

ALTER PLUGGABLE DATABASE pdb2 OPEN READ WRITE;

COLUMN pdb_name FORMAT A20

SELECT
    pdb_name,
    status
FROM
    dba_pdbs
ORDER BY
    pdb_name;

COLUMN name FORMAT A20

SELECT
    name,
    open_mode
FROM
    v$pdbs
ORDER BY
    name;

SHOW PDBS;