-- con_SYS_21c

ALTER PLUGGABLE DATABASE shard1 CLOSE;

ALTER PLUGGABLE DATABASE shard1 UNPLUG INTO 'C:\Users\admin\Downloads\WINDOWS.X64_213000_db_home\oradata\shard1.xml';

DROP PLUGGABLE DATABASE shard1;